"""Configuration: a tiny stdlib ``.env`` reader/writer and a settings snapshot.

No third-party dependencies. ``.env`` lives at the repository root (next to
``run.py``) and holds the user's secrets; it is git-ignored.
"""
from __future__ import annotations

import os
from pathlib import Path

# Repo root = parent of this package directory.
ROOT = Path(__file__).resolve().parents[1]
ENV_PATH = ROOT / ".env"


def load_env(path: Path = ENV_PATH) -> dict:
    """Parse ``.env`` into a dict and push values into ``os.environ``.

    Lines are ``KEY=VALUE``; blank lines and ``#`` comments are ignored.
    Surrounding quotes are stripped. Existing environment variables win, so a
    real environment can override the file.
    """
    data: dict[str, str] = {}
    if not path.exists():
        return data
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        data[key] = value
        os.environ.setdefault(key, value)
    return data


def write_env(values: dict, path: Path = ENV_PATH) -> None:
    """Write ``values`` to ``.env`` with restrictive permissions (0600).

    Only non-empty values are written. A short header reminds the reader that
    the file is secret.
    """
    lines = [
        "# Threadloom settings — generated by the setup wizard.",
        "# Contains secrets. Never commit this file (it is in .gitignore).",
        "",
    ]
    for key, value in values.items():
        if value is None or value == "":
            continue
        lines.append(f"{key}={value}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    try:
        path.chmod(0o600)
    except OSError:
        pass


class Config:
    """A read-only snapshot of the current settings, taken from the environment."""

    def __init__(self) -> None:
        load_env()
        self.lang = os.environ.get("LANG_UI", "en")
        self.telegram_token = os.environ.get("TELEGRAM_TOKEN", "")
        self.owner_id = os.environ.get("OWNER_ID", "")
        self.threads_user_id = os.environ.get("THREADS_USER_ID", "")
        self.threads_token = os.environ.get("THREADS_ACCESS_TOKEN", "")
        # Optional final reply appended to every thread (e.g. a link to your channel).
        self.cta = os.environ.get("THREADS_CTA", "")
        # Optional LLM splitter.
        self.llm_enabled = os.environ.get("LLM_ENABLED", "").lower() in ("1", "true", "yes")
        self.llm_provider = os.environ.get("LLM_PROVIDER", "openai")  # "openai" | "anthropic"
        self.llm_base = os.environ.get("LLM_API_BASE", "https://api.openai.com/v1")
        self.llm_key = os.environ.get("LLM_API_KEY", "")
        self.llm_model = os.environ.get("LLM_MODEL", "")

    @property
    def threads_ready(self) -> bool:
        return bool(self.threads_user_id and self.threads_token)

    @property
    def configured(self) -> bool:
        """True once the minimum to run the bot exists (a Telegram token + owner)."""
        return bool(self.telegram_token and self.owner_id)
